print("Hi, I am a Great Magician. What is your name?")
name = input()
print("Welcome " + name + ", I am going to perform a mind trick on you")
print("Let me show you a magic!")
number = int(input("Pick a number between 1 and 10: "))
final_answer = int (((number * 2) *5 )/ number - 7 )
print("Multiply the number by 2")
print("Multiply the new number by 5")
print("Divide the current number by the original number")
print("Subtract 7 from the current number")
print("Tell me if you finish counting.")
counting = input()
print("now, I am going to guess your current number by read your mind")
print(".......... I knew it now!")
print("Your current number is " + str(final_answer) + ".")